<?php

namespace MasterStudy\Lms\Pro\AddonsPlus\AiLab\Services\OpenAi;

use MasterStudy\Lms\Pro\AddonsPlus\AiLab\Services\OpenAi\Queries\Query;

final class Response {
	public Query $query;

	/**
	 * contains items generated by the AI
	 */
	public array $results = array();

	/**
	 * contains the raw response from the API
	 */
	public array $raw;

	public function __construct( Query $query, array $results, array $raw ) {
		$this->query   = $query;
		$this->results = $results;
		$this->raw     = $raw;
	}
}
